run-mode: debug

http:
  port: 3344
  read-timeout: 60
  write-timeout: 60

database:
  type: mysql
  host: 127.0.0.1:3306
  name: db_vid
  charset: utf8
  user: root
  password: 123

jwt:
  secret: 9C27D0C7C04BDA8A1F1B099CF4F9B1956AF5164F
  expire: 1800 # s

format:
  min-username: 4
  max-username: 30
  min-password: 8
  max-password: 30
