run-mode: debug

http:
  port: 3344

database:
  type: mysql
  host: 127.0.0.1
  port: 3306
  name: db_vid
  charset: utf8
  user: root
  password: 123
  log: true
  page-size: 5

jwt:
  secret: 9C27D0C7C04BDA8A1F1B099CF4F9B1956AF5164F
  expire: 604800 # second
  issuer: vid.srv.auth
  redis-header: vid_token
