basePath: /
host: localhost:3344
info:
  description: Backend of repo https://github.com/vidorg/vid_vue
  license:
    name: MIT
    url: https://github.com/vidorg/vid_backend/blob/master/LICENSE
  termsOfService: https://github.com/vidorg
  title: vid backend
  version: '1.1'
paths:
  /auth/:
    get:
      consumes:
      - multipart/form-data
      description: '根据认证 token 查看当前用户，Auth


        | code | message |

        | --- | --- |

        | 400 | request form data exception |

        | 401 | authorization failed |

        | 401 | token has expired | '
      operationId: -auth-get
      parameters:
      - description: 用户 Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        '200':
          description: "```json\n{\n  \"code\": 200,\n  \"message\": \"Success\",\n\
            \  \"data\": {\n    \"uid\": 10,\n    \"username\": \"aoihosizora\",\n\
            \    \"sex\": \"unknown\",\n    \"profile\": \"\",\n    \"avatar_url\"\
            : \"\",\n    \"birth_time\": \"2000-01-01\",\n    \"authority\": \"normal\"\
            \n  }\n}\n```"
      summary: 查看当前用户
  /auth/login:
    post:
      consumes:
      - multipart/form-data
      description: '用户登录，Non-Auth


        | code | message |

        | --- | --- |

        | 400 | request form data exception |

        | 401 | password error |

        | 404 | user not found |

        | 500 | login failed | '
      operationId: -auth-login-post
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 用户密码
        in: formData
        name: password
        required: true
        type: string
      - description: 登录有效期，默认一个小时
        in: formData
        name: expire
        required: false
        type: integer
      produces:
      - application/json
      responses:
        '200':
          description: "```json\n{\n  \"code\": 200,\n  \"message\": \"Success\",\n\
            \  \"data\": {\n    \"user\": {\n      \"uid\": 10,\n      \"username\"\
            : \"aoihosizora\",\n      \"sex\": \"unknown\",\n      \"profile\": \"\
            \",\n      \"avatar_url\": \"\",\n      \"birth_time\": \"2000-01-01\"\
            ,\n      \"authority\": \"normal\"\n    },\n    \"token\": \"Bearer xxx\"\
            \n  }\n}\n```"
      summary: 登录
  /auth/pass:
    post:
      consumes:
      - multipart/form-data
      description: '用户修改密码，Auth


        | code | message |

        | --- | --- |

        | 400 | request form data exception |

        | 401 | authorization failed |

        | 401 | token has expired |

        | 404 | user not found |

        | 500 | update password failed | '
      operationId: -auth-pass-post
      parameters:
      - description: 用户 Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户新密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        '200':
          description: "```json\n{\n  \"code\": 200,\n  \"message\": \"Success\",\n\
            \  \"data\": {\n    \"uid\": 10,\n    \"username\": \"aoihosizora\",\n\
            \    \"sex\": \"unknown\",\n    \"profile\": \"\",\n    \"avatar_url\"\
            : \"\",\n    \"birth_time\": \"2000-01-01\",\n    \"authority\": \"normal\"\
            \n  }\n}\n```"
      summary: 修改密码
  /auth/register:
    post:
      consumes:
      - multipart/form-data
      description: '用户注册，Non-Auth


        | code | message |

        | --- | --- |

        | 400 | request form data exception |

        | 500 | username duplicated |

        | 500 | register failed | '
      operationId: -auth-register-post
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 用户密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        '200':
          description: "```json\n{\n  \"code\": 200,\n  \"message\": \"Success\",\n\
            \  \"data\": {\n    \"uid\": 10,\n    \"username\": \"aoihosizora\",\n\
            \    \"sex\": \"unknown\",\n    \"profile\": \"\",\n    \"avatar_url\"\
            : \"\",\n    \"birth_time\": \"2000-01-01\",\n    \"authority\": \"normal\"\
            \n  }\n}\n```"
      summary: 注册
  /user/:
    delete:
      consumes:
      - multipart/form-data
      description: '删除用户所有信息，Auth


        | code | message |

        | --- | --- |

        | 401 | authorization failed |

        | 401 | token has expired |

        | 404 | user not found |

        | 404 | user delete failed | '
      operationId: -user-delete
      parameters:
      - description: 用户 Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        '200':
          description: "```json\n{\n  \"code\": 200,\n  \"message\": \"Success\"\n\
            }\n```"
      summary: 删除用户
    get:
      consumes:
      - multipart/form-data
      description: '管理员查询所有用户，返回分页数据，Admin


        | code | message |

        | --- | --- |

        | 401 | authorization failed |

        | 401 | token has expired |

        | 401 | need admin authority | '
      operationId: -user-get
      parameters:
      - description: 用户 Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 分页
        in: query
        name: page
        required: false
        type: integer
      produces:
      - application/json
      responses:
        '200':
          description: "```json\n{\n  \"code\": 200,\n  \"message\": \"Success\",\n\
            \  \"data\": {\n    \"count\": 1,\n    \"page\": 1,\n    \"data\": [\n\
            \      {\n        \"uid\": 1,\n        \"username\": \"User1\",\n    \
            \    \"sex\": \"male\",\n        \"profile\": \"\",\n        \"avatar_url\"\
            : \"\",\n        \"birth_time\": \"2000-01-01\",\n        \"authority\"\
            : \"admin\"\n      }\n    ]\n  }\n}\n```"
      summary: 查询所有用户
    put:
      consumes:
      - multipart/form-data
      description: '更新用户信息，Auth


        | code | message |

        | --- | --- |

        | 401 | authorization failed |

        | 401 | token has expired |

        | 404 | user not found |

        | 500 | user update failed | '
      operationId: -user-put
      parameters:
      - description: 用户 Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 新用户名
        in: formData
        name: username
        required: false
        type: string
      - description: 新用户性别，只允许为 (male, female, unknown)
        in: formData
        name: sex
        required: false
        type: string
      - description: 新用户简介
        in: formData
        name: profile
        required: false
        type: string
      - description: 新用户生日，固定格式为 2000-01-01
        in: formData
        name: birth_time
        required: false
        type: string
      - description: 新用户电话号码
        in: formData
        name: phone_number
        required: false
        type: string
      produces:
      - application/json
      responses:
        '200':
          description: "```json\n{\n  \"code\": 200,\n  \"message\": \"Success\",\n\
            \  \"data\": {\n    \"uid\": 10,\n    \"username\": \"aoihosizora\",\n\
            \    \"sex\": \"male\",\n    \"profile\": \"Demo Profile\",\n    \"avatar_url\"\
            : \"\",\n    \"birth_time\": \"2019-12-18\",\n    \"authority\": \"admin\"\
            \n  }\n}\n```"
      summary: 更新用户
  /user/sub:
    post:
      consumes:
      - multipart/form-data
      description: '关注某一用户，Auth


        | code | message |

        | --- | --- |

        | 400 | request query param exception |

        | 400 | subscribe oneself invalid |

        | 401 | authorization failed |

        | 401 | token has expired |

        | 404 | user not found |

        | 500 | subscribe failed | '
      operationId: -user-sub-post
      parameters:
      - description: 用户 Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 对方用户 id
        in: query
        name: uid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        '200':
          description: "```json\n{\n  \"code\": 200,\n  \"message\": \"Success\",\n\
            \  \"data\": {\n    \"me\": 10,\n    \"up\": 3,\n    \"action\": \"subscribe\"\
            \n  }\n}\n```"
      summary: 关注用户
  /user/unsub:
    post:
      consumes:
      - multipart/form-data
      description: '取消关注某一用户，Auth


        | code | message |

        | --- | --- |

        | 400 | request query param exception |

        | 401 | authorization failed |

        | 401 | token has expired |

        | 404 | user not found |

        | 500 | unsubscribe failed | '
      operationId: -user-unsub-post
      parameters:
      - description: 用户 Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 对方用户 id
        in: query
        name: uid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        '200':
          description: "```json\n{\n  \"code\": 200,\n  \"message\": \"Success\",\n\
            \  \"data\": {\n    \"me\": 10,\n    \"up\": 3,\n    \"action\": \"unsubscribe\"\
            \n  }\n}\n```"
      summary: 取消关注用户
  /user/{uid}:
    get:
      consumes:
      - multipart/form-data
      description: '普通用户查询用户信息，Non-Auth


        | code | message |

        | --- | --- |

        | 400 | request route param exception |

        | 404 | user not found | '
      operationId: -user-{uid}-get
      parameters:
      - description: 用户 id
        in: path
        name: uid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        '200':
          description: "```json\n{\n  \"code\": 200,\n  \"message\": \"Success\",\n\
            \  \"data\": {\n    \"user\": {\n      \"uid\": 10,\n      \"username\"\
            : \"aoihosizora\",\n      \"sex\": \"unknown\",\n      \"profile\": \"\
            \",\n      \"avatar_url\": \"\",\n      \"birth_time\": \"2000-01-01\"\
            ,\n      \"authority\": \"admin\"\n    },\n    \"extra\": {\n      \"\
            subscribing_cnt\": 1,\n      \"subscriber_cnt\": 2,\n      \"video_cnt\"\
            : 0,\n      \"playlist_cnt\": 0\n    }\n  }\n}\n```"
      summary: 查询用户
  /user/{uid}/subscriber:
    get:
      consumes:
      - multipart/form-data
      description: '查询用户所有粉丝，返回分页数据，Non-Auth


        | code | message |

        | --- | --- |

        | 400 | request route param exception |

        | 404 | user not found | '
      operationId: -user-{uid}-subscriber-get
      parameters:
      - description: 所查询的用户 id
        in: path
        name: uid
        required: true
        type: integer
      - description: 分页
        in: query
        name: page
        required: false
        type: integer
      produces:
      - application/json
      responses:
        '200':
          description: "```json\n{\n  \"code\": 200,\n  \"message\": \"Success\",\n\
            \  \"data\": {\n    \"count\": 2,\n    \"page\": 1,\n    \"data\": [\n\
            \      {\n        \"uid\": 1,\n        \"username\": \"User1\",\n    \
            \    \"sex\": \"male\",\n        \"profile\": \"\",\n        \"avatar_url\"\
            : \"\",\n        \"birth_time\": \"2000-01-01\",\n        \"authority\"\
            : \"admin\"\n      },\n      {\n        \"uid\": 2,\n        \"username\"\
            : \"User2\",\n        \"sex\": \"unknown\",\n        \"profile\": \"\"\
            ,\n        \"avatar_url\": \"\",\n        \"birth_time\": \"2000-01-01\"\
            ,\n        \"authority\": \"normal\"\n      }\n    ]\n  }\n}\n```"
      summary: 用户粉丝
  /user/{uid}/subscribing:
    get:
      consumes:
      - multipart/form-data
      description: '查询用户所有关注，返回分页数据，Non-Auth


        | code | message |

        | --- | --- |

        | 400 | request route param exception |

        | 404 | user not found | '
      operationId: -user-{uid}-subscribing-get
      parameters:
      - description: 所查询的用户 id
        in: path
        name: uid
        required: true
        type: integer
      - description: 分页
        in: query
        name: page
        required: false
        type: integer
      produces:
      - application/json
      responses:
        '200':
          description: "```json\n{\n  \"code\": 200,\n  \"message\": \"Success\",\n\
            \  \"data\": {\n    \"count\": 1,\n    \"page\": 1,\n    \"data\": [\n\
            \      {\n        \"uid\": 1,\n        \"username\": \"User1\",\n    \
            \    \"sex\": \"male\",\n        \"profile\": \"\",\n        \"avatar_url\"\
            : \"\",\n        \"birth_time\": \"2000-01-01\",\n        \"authority\"\
            : \"admin\"\n      }\n    ]\n  }\n}\n```"
      summary: 用户关注的人
swagger: '2.0'
